/* The Open Door Index — shareable maps.
   A small gallery of the three high-res share graphics (3200x2000 PNGs in
   public/open-door/maps/, generated by scripts/share-maps/). Free to repost
   with credit. Route: /passport-insights/maps */

import Head from 'next/head'

const MAPS = [
  {
    file: 'map3-open-door-index.png',
    eyebrow: 'PASSPORT STRENGTH',
    title: 'Passport strength, by where humans actually go',
    blurb:
      'The index itself. Every passport scored by the total yearly tourist flow of the places it enters without a pre-arranged visa — not by counting countries.',
  },
  {
    file: 'map1-hospitality-balance.png',
    eyebrow: 'HOSPITALITY BALANCE',
    title: 'Who holds the door open — and who just walks through',
    blurb:
      'Green countries give more hospitality than they receive; red countries receive more than they give. Both sides measured in travel flow, not country counts.',
  },
  {
    file: 'map2-hosts-and-guests.png',
    eyebrow: 'HOSTS & GUESTS',
    title: 'Host nations and guest nations',
    blurb:
      'Indigo hosts pull in more international tourists than their residents travel out. Orange guests travel out more than the world comes to them.',
  },
]

const OG = 'https://aiandtractors.com/open-door/maps/map3-open-door-index.png'

export default function PassportMaps() {
  return (
    <>
      <Head>
        <title>Shareable maps — The Open Door Index | Ivan Braun</title>
        <meta
          name="description"
          content="Three high-resolution maps from the Open Door Index, free to repost with credit: passport strength by tourism flow, hospitality balance, and host vs guest nations."
        />
        <link rel="canonical" href="https://aiandtractors.com/passport-insights/maps" />
        <meta property="og:title" content="Shareable maps — The Open Door Index" />
        <meta
          property="og:description"
          content="Passport strength by where humans actually go, hospitality balance, and host vs guest nations. Free to repost with credit."
        />
        <meta property="og:image" content={OG} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:image" content={OG} />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="/open-door/noe.css" />
        <link rel="stylesheet" href="/open-door/styles.css" />
      </Head>

      <header className="topnav">
        <div className="topnav-inner">
          <a className="topnav-brand pixel-brand" href="/passport-ranking">Ivan Braun</a>
          <nav className="topnav-links">
            <a href="/experience">Experience</a>
            <a href="/book">Book</a>
            <a href="/tech-events-2026">Tech Events</a>
            <a href="/passport-ranking" className="is-active">Passport Ranking</a>
            <a href="/contact">Contact</a>
          </nav>
          <div className="topnav-langs" aria-hidden="true">🇺🇸 🇦🇷 🇧🇷</div>
        </div>
      </header>

      <main className="sm-page">
        <section className="sm-hero">
          <div className="sm-eyebrow">THE OPEN DOOR INDEX · SHAREABLE MAPS</div>
          <h1 className="sm-title">Three maps. Free to repost.</h1>
          <p className="sm-sub">
            High-resolution graphics built straight from the dataset — 3200×2000,
            ready for r/MapPorn, r/dataisbeautiful, a deck, or a post. Take any of
            them; a credit to <strong>aiandtractors.com/passport-ranking</strong> is
            all we ask.
          </p>
          <div className="sm-hero-links">
            <a className="sm-link" href="/passport-ranking">Open the ranking →</a>
            <span className="sm-sep">·</span>
            <a className="sm-link" href="/passport-insights">Key findings →</a>
            <span className="sm-sep">·</span>
            <a className="sm-link" href="/passport-insights/methodology">Methodology →</a>
          </div>
        </section>

        <div className="sm-grid">
          {MAPS.map((m) => {
            const src = `/open-door/maps/${m.file}`
            return (
              <figure className="sm-card" key={m.file}>
                <a className="sm-frame" href={src} target="_blank" rel="noopener noreferrer" title="Open full size">
                  <img src={src} alt={m.title} loading="lazy" width="1600" height="1000" />
                </a>
                <figcaption className="sm-cap">
                  <div className="sm-card-eyebrow">{m.eyebrow}</div>
                  <h2 className="sm-card-title">{m.title}</h2>
                  <p className="sm-card-blurb">{m.blurb}</p>
                  <div className="sm-actions">
                    <a className="sm-btn sm-btn--primary" href={src} download>
                      Download PNG · 3200×2000
                    </a>
                    <a className="sm-btn" href={src} target="_blank" rel="noopener noreferrer">
                      View full size
                    </a>
                  </div>
                </figcaption>
              </figure>
            )
          })}
        </div>

        <footer className="sm-foot">
          <p>
            Visa data: <a href="https://github.com/visualpharm/visa-free-dataset" target="_blank" rel="noopener noreferrer">github.com/visualpharm/visa-free-dataset</a>{' '}
            · Destination volumes: UN Tourism (World Bank fallback) · Borders simplified;
            colors show tourism data, not political status.
          </p>
          <p className="sm-foot-mono">Free to share with credit · Build · 2026.06</p>
        </footer>
      </main>

      <style jsx>{`
        .sm-page {
          max-width: 1100px;
          margin: 0 auto;
          padding: 56px 24px 96px;
          font-family: Inter, -apple-system, BlinkMacSystemFont, sans-serif;
          color: #1c1d22;
        }
        .sm-hero { max-width: 760px; margin-bottom: 44px; }
        .sm-eyebrow {
          font-family: 'DotGothic16', monospace;
          font-size: 14px;
          letter-spacing: 0.2em;
          color: #5e6ad2;
          margin-bottom: 14px;
        }
        .sm-title {
          font-size: 42px;
          font-weight: 800;
          letter-spacing: -0.02em;
          line-height: 1.05;
          margin: 0 0 16px;
        }
        .sm-sub { font-size: 18px; line-height: 1.55; color: #4a4b55; margin: 0 0 18px; }
        .sm-sub strong { color: #1c1d22; font-weight: 600; }
        .sm-hero-links { font-size: 15px; }
        .sm-link { color: #5e6ad2; text-decoration: none; font-weight: 600; }
        .sm-link:hover { text-decoration: underline; }
        .sm-sep { color: #c7c8d0; margin: 0 10px; }

        .sm-grid { display: flex; flex-direction: column; gap: 56px; }
        .sm-card { margin: 0; }
        .sm-frame {
          display: block;
          border: 1px solid rgba(0, 0, 0, 0.08);
          border-radius: 12px;
          overflow: hidden;
          background: #fbfaf8;
          box-shadow: 0 1px 4px rgba(0, 0, 0, 0.04);
          transition: box-shadow 0.18s ease, transform 0.18s ease;
        }
        .sm-frame:hover { box-shadow: 0 6px 22px rgba(0, 0, 0, 0.1); transform: translateY(-2px); }
        .sm-frame img { display: block; width: 100%; height: auto; }

        .sm-cap { margin-top: 18px; max-width: 760px; }
        .sm-card-eyebrow {
          font-family: 'DotGothic16', monospace;
          font-size: 12px;
          letter-spacing: 0.14em;
          color: #5e6ad2;
          margin-bottom: 8px;
        }
        .sm-card-title { font-size: 24px; font-weight: 700; letter-spacing: -0.01em; margin: 0 0 8px; }
        .sm-card-blurb { font-size: 16px; line-height: 1.55; color: #4a4b55; margin: 0 0 16px; }

        .sm-actions { display: flex; flex-wrap: wrap; gap: 12px; }
        .sm-btn {
          display: inline-block;
          padding: 10px 18px;
          border-radius: 8px;
          font-size: 14.5px;
          font-weight: 600;
          text-decoration: none;
          border: 1px solid rgba(0, 0, 0, 0.12);
          color: #1c1d22;
          background: #fff;
          transition: background 0.15s ease, border-color 0.15s ease;
        }
        .sm-btn:hover { border-color: rgba(0, 0, 0, 0.28); }
        .sm-btn--primary { background: #5e6ad2; border-color: #5e6ad2; color: #fff; }
        .sm-btn--primary:hover { background: #4c57bf; border-color: #4c57bf; }

        .sm-foot {
          margin-top: 64px;
          padding-top: 22px;
          border-top: 1px solid rgba(0, 0, 0, 0.08);
          font-size: 13px;
          color: #8a8b94;
          line-height: 1.6;
        }
        .sm-foot a { color: #5e6ad2; text-decoration: none; }
        .sm-foot a:hover { text-decoration: underline; }
        .sm-foot-mono { font-family: 'DotGothic16', monospace; letter-spacing: 0.06em; margin-top: 6px; }

        @media (max-width: 640px) {
          .sm-page { padding: 36px 16px 72px; }
          .sm-title { font-size: 32px; }
          .sm-sub { font-size: 16px; }
          .sm-grid { gap: 40px; }
          .sm-card-title { font-size: 20px; }
        }
      `}</style>
    </>
  )
}
